/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weihung' at '2016/8/25 下午 9:48' with Gradle 3.0
 *
 * @author weihung, @date 2016/8/25 下午 9:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
